config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tweets/index'
  root to: "tweets#index"
  resources :users, only: [:edit, :update, :show] do
    resources :memories
    resources :favorites
  end
  resources :tweets, only: [:index, :new, :create,:show, :destroy] do
    collection do
      get :search
    end
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet, dependent: :destroy
  belongs_to :user, dependent: :destroy

  validates :text, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates_uniqueness_of :tweet_id, scope: :user_id

end

app/models/memory.rb
class Memory < ApplicationRecord
  belongs_to :user

  def start_time
    self.memory_date
  end

  with_options presence: true do
    validates :title
    validates :memory_date
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  enum genre:{
    month_1:  1,
    month_2:  2,
    month_3:  3,
    month_6:  4,
    month_8:  5,
    month_10: 6,
    year_1:   7,
    year_1_5: 8,
    year_2:   9,
    year_3:   10,
    year_4:   11,
    year_5:   12,
    year_6:   13,
    year_7:   14,
    overyear: 15 
  }

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :image
    validates :title
    validates :content
    validates :genre
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :comments, dependent: :destroy
  has_many :memories
  has_many :favorites, dependent: :destroy

  def already_favorited?(tweet)
    self.favorites.exists?(tweet_id: tweet.id)
  end

  with_options presence: true do
    validates :nickname
    validates :birthday
  end

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :birthday, :profile])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to [@tweet]
    else
      render 'tweets/show'
    end
  end

  def destroy
    comment = current_user.comments.find(params[:id])
    comment.destroy

    redirect_to [:tweet, {id: params[:tweet_id]}]
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, only:[:create, :destroy]

  def index
    @tweets = Tweet.joins(:favorites).where(favorites: { user_id: params[:user_id]})
  end

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @favorite = current_user.favorites.create(tweet_id: params[:tweet_id])
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @favorite = current_user.favorites.find_by(tweet_id: @tweet.id)
    @favorite.destroy
  end
end

app/controllers/memories_controller.rb
class MemoriesController < ApplicationController
  before_action :set_memory, only:[:show, :edit, :update, :destroy]
  before_action :set_user

  def new
    @memory = current_user.memories.new
    @user = current_user
  end

  def create
    @memory = current_user.memories.new(memory_params)
    if @memory.save
      redirect_to user_path(@user.id)
    else
      redirect_to new_user_memory_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @memory.update(memory_params)
    redirect_to user_memory_path(@user.id)
  end
  
  def destroy
    @memory.destroy
    redirect_to user_path(@user.id)
  end





  private

  def memory_params
    params.require(:memory).permit(:title, :content, :memory_date).merge(user_id: current_user.id)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_memory
    @memory = current_user.memories.find(params[:id])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @tweets = Tweet.all.order(created_at: :desc)
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    @tweets = Tweet.all.order(created_at: :desc)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end

  def search
    genre = params[:genre]
    @tweets = Tweet.where(genre: genre).order(created_at: :desc)
    @tweet = Tweet.new
    render :index
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :content, :genre, :image).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def edit
    @user = current_user
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @memories = Memory.where(user_id: @user.id)
    @memory = Memory.new
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :profile)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if current_user.already_favorited?(tweet) %>
    <%= link_to tweet_favorites_path(tweet), method: :delete, remote: true do %>
      <i class="fas fa-heart"></i>
    <% end %>
  <% else %>
    <%= link_to tweet_favorites_path(tweet), method: :post, remote: true do %>
      <i class="far fa-heart"></i>
    <% end %>
  <% end %>
<% else %>
  <i class="far fa-heart"></i>
<% end %>
<%= tweet.favorites.count %>

app/views/favorites/create.js.erb
$("#favorites-<%= @tweet.id %>").html("<%= escape_javascript(render partial: 'favorites/favorite', locals: { tweet: @tweet}) %>");

app/views/favorites/destroy.js.erb
$("#favorites-<%= @tweet.id %>").html("<%= escape_javascript(render partial: 'favorites/favorite', locals: { tweet: @tweet}) %>");

app/views/favorites/index.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-8 mx-auto">
      <div class="card mt-3">
        <% @tweets.each do |tweet| %>
          <%= link_to [tweet] do %>
            <div class=" card-image-top text-center mt-3 ">
              <%= image_tag tweet.image,  class: "img-fluid img-thumbnail" %>
            </div>
          <% end %>
          <div class="card-body">
          <% if user_signed_in? && current_user.id == tweet.user_id %>
            <%= link_to "削除", tweet_path(tweet.id), method: :delete, class: "btn btn-danger btn-sm" %>
            <% end%>
            <h4 class="card-title text-center"><%= tweet.title %></h4>
            <ul class="list-group">
              <li class="list-group-item">投稿者名:<%= tweet.user.nickname %></li>
              <li class="list-group-item"><%= simple_format tweet.content %></li>
              <li class="list-group-item">
              <%= link_to tweet.genre_i18n, search_tweets_path(genre: tweet.genre) %>
              </li> 
            </ul>
            <div id="favorites-<%= tweet.id %>">
              <%= render partial: "favorites/favorite", locals: { tweet: tweet } %>
            </div>
            
            
            <p class="text-right">
              <small class="text-muted">更新日：<%= tweet.updated_at.strftime("%Y-%m-%d") %></small>
            </p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Babylife</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"> %>
    <script src="https://kit.fontawesome.com/42fed437c3.js" crossorigin="anonymous"></script>
</head>
<%= render "shared/header" %>

<body>


  <main class="pt-3">
  <% if flash[:notice] %>
  <div class="alert alert-primary" role="alert"><strong><%= notice %></strong></div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert"><strong><%= alert %></strong></div>
<% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous">
    </script>
  </main>
</body>

</html>

app/views/memories/edit.html.erb
<div class= "container pt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <%= form_with model: [@user, @memory], local: true do |f| %>
        <div class="form-group">
          <%= f.label :memory_date, "記念日" %>
          <%= f.date_field :memory_date, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :title, "記録" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :content, "詳細記録" %>
          <%= f.text_area :content, class: "form-control" %>
        </div>
        <%= f.submit "更新", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/memories/new.html.erb
<div class= "container pt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <%= form_with model: [@user, @memory], local: true do |f| %>
        <div class="form-group">
          <%= f.label :memory_date, "記念日" %>
          <%= f.date_field :memory_date, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :title, "記録" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :content, "詳細記録" %>
          <%= f.text_area :content, class: "form-control" %>
        </div>
        <%= f.submit "記録", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/memories/show.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-10 mx-auto">
　　　　<div class="card">
  　　　<h2 class="text-center">記録</h2>
  <% if user_signed_in? %>
  <ul class="nav nav-tabs">
      <%= link_to "編集", edit_user_memory_path(@user, @memory), method: :get, class: "btn btn-success" %>
    
      <%= link_to "削除", user_memory_path(@user, @memory), method: :delete, class: "btn btn-danger" %>
  </ul>
  <% end %>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <%= @memory.memory_date %>
    </li>
    <li class="list-group-item">
      <%= @memory.title %>
    </li>
    <li class="list-group-item">
      <%= simple_format(@memory.content) %>
    </li>
  </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_calender.html.erb
<% if user_signed_in? && current_user.id == @user.id %>
<div class="container pt-5">
  <div class="row">
    <div class="col-12">
      <div class="card">
      <%= link_to "記録する", new_user_memory_path(@user.id), class: "btn btn-info" %>
        <div class="card-body">
          <%= month_calendar events: @memories do |date, memories| %>
          <%= date.day %>
            <% memories.each do |memory| %>
              <%= link_to memory.title, user_memory_path(@user, memory) %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <div>
</div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark bg-info fixed-top p-3 ">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">BabyLife <i class="fas fa-baby"></i></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user.nickname, user_path(current_user), class: "nav-link" %>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <% if controller_name == 'tweets' && action_name == 'index' %>
          <li class="nav-item">
            <button type="button" class="reset-btn" data-toggle="modal" data-target="#exampleModal">
              新規投稿
            </button>
          </div>
          </li>
          <% end %>
          <% else %>
          <li class="nav-item">
            <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to '新規登録', new_user_registration_path, class: "nav-link" %>
          </li>
          <% end %>
            <%# <% if user_signed_in? %>
 
    <%# <% end %> 
          <%# <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown"
              aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown01">
              <li><a class="dropdown-item" href="#"></a></li>
              <li><a class="dropdown-item" href="#"></a></li>
              
            </ul>
          </li> %>
        </ul>
      </div>
    </div>
  </nav>
    
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tweets/_tweet.html.erb
<div class="card mt-3">
  <%= link_to [tweet] do %>
    <div class=" card-image-top text-center mt-3 ">
      <%= image_tag tweet.image,  class: "img-fluid img-thumbnail" %>
    </div>
  <% end %>
  <div class="card-body">
  <% if user_signed_in? && current_user.id == tweet.user_id %>
    <%= link_to "削除", tweet_path(tweet.id), method: :delete, class: "btn btn-danger btn-sm" %>
    <% end%>
    <h4 class="card-title text-center"><%= tweet.title %></h4>
    <ul class="list-group">
      <li class="list-group-item">投稿者名:<%= tweet.user.nickname %></li>
      <li class="list-group-item"><%= simple_format tweet.content %></li>
      <li class="list-group-item">
      <%= link_to tweet.genre_i18n, search_tweets_path(genre: tweet.genre) %>
      </li> 
    </ul>
    <div id="favorites-<%= tweet.id %>">
      <%= render partial: "favorites/favorite", locals: { tweet: tweet } %>
    </div>
    
    
    <p class="text-right">
      <small class="text-muted">更新日：<%= tweet.updated_at.strftime("%Y-%m-%d") %></small>
    </p>
  </div>
</div>

app/views/tweets/create.js.erb
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide')
$('.tweets').html("<%= escape_javascript(render partial: 'tweet', collection: @tweets, as: :tweet) %>")

app/views/tweets/index.html.erb
<div class="container pt-5">
  <div class="row">

    <div class="col-10 mx-auto">
      <h1 class="text-center">みんなの投稿</h1>
    </div>
      <div class="tweets col-8 mx-auto">
        <%= render partial: "tweet", collection: @tweets, as: :tweet %>
      </div>
  </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">新規投稿</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with model: @tweet, remote: true do |f| %>
      <div class="modal-body">
        <div>
          <%= f.file_field :image %>
        </div>
        <div class="form-group">
          <%= f.label :title, "タイトル" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :content, "内容" %>
          <%= f.text_area :content, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :genre, "生後" %>
          <%= f.select :genre, Tweet.genres.keys.map{|k| [I18n.t("enums.tweet.genre.#{k}"), k]},{prompt:'選択してください'}, class: "form-control" %>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        <%= f.submit "投稿する", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-10 mx-auto">
      <h1 class="text-center">詳細ページ</h1>
    </div>
    <div class="col-8 mx-auto">
      <div class="card mt-3">
        <picture class=" card-image-top text-center mt-3">
        <%= image_tag @tweet.image, class: "img-fluid img-thumbnail" %>
        </picture>
        <div class="card-body">
        <% if user_signed_in? && current_user.id == @tweet.user_id %>
          <%= link_to "削除", tweet_path(@tweet.id), method: :delete, class: "btn btn-danger btn-sm" %>
          <% end%>
          <h4 class="card-title text-center"><%= @tweet.title %></h4>
          <ul class="list-group">
            <li class="list-group-item">投稿者名:<%= @tweet.user.nickname %></li>
            <li class="list-group-item"><%= simple_format @tweet.content %></li>
            <li class="list-group-item">
              <%= link_to @tweet.genre_i18n, search_tweets_path(genre: @tweet.genre) %>
            </li> 
          </ul>
          <div id="favorites-<%= @tweet.id %>">
          <%= render 'favorites/favorite', tweet: @tweet %>
          </div>
          
          <p class="text-right">
            <small class="text-muted">更新日：<%= @tweet.updated_at.strftime("%Y-%m-%d") %></small>
          </p>
         </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <div class="card">
        <div class="card-body">
        <% if user_signed_in? %>
        <%= form_with model: [@tweet, @comment], local: true do |f| %>
        <div class="form-group">
        <%= f.text_field :text, placeholder: "コメントを追加", class: "form-control" %>
        <%= f.submit "送信", class: "btn btn-primary mt-2" %>
        </div>
        <% end %>
        <% end %>

        <% @tweet.comments.each do |comment| %>
        <p>
          <%= comment.text %>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <% if comment.user == current_user %>
          <%= link_to '削除', [@tweet, comment], method: :delete, class: "btn btn-danger btn-sm" %>
          <% end %>
        </p>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class= "container pt-5">
  <div class="row">
    <div class="col-6 mx-auto">
      <h2>アカウント編集</h2>
      <%= link_to "ログアウト", "#"%>
      <%= link_to "戻る", :back%>
      <%= form_with model: current_user, local: true do |f|%>
        <div class="form-group">
          <%= f.label :nickname, "ユーザー名" %>
          <%= f.text_field :nickname, autofocus: true, class: "form-control" %>
        </div>
        <div class='form-group'>
          <%= f.label :email%>
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class='form-group'>
          <%= f.label :password%>
          <i>(英数字6文字以上)</i>
          <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
        </div>
        <div class='form-group'>
          <%= f.label :profile, "自己紹介文"%>
          <%= f.text_area :profile, class: "form-control" %>
        </div>
        <%= f.submit "update", class: 'btn btn-success'%>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-8 mx-auto">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title text-center"><%= @user.nickname%>のページ</h5>
            <% if user_signed_in? && current_user.id == @user.id %>
              <%= link_to "ユーザー編集", edit_user_path(@user.id), method: :get, class: "btn btn-success" %>
            <% end %>
            <ul class="list-group">
              <li class="list-group-item">生年月日:<%= @user.birthday %></li>
              <li class="list-group-item"><%= simple_format @user.profile %></li>
              <li class="list-group-item"><%= link_to 'いいね一覧', [@user, :favorites] %></li>
            </ul>
        </div>
      </div>
    </div>
 
    <%= render 'shared/calender' %>

    <div class="col-10 mx-auto">
    <% @user.tweets.each do |tweet| %>
    <%= render 'tweets/tweet', tweet: tweet  %>
    <% end %>
  </div>
</div>